apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-compositions
  namespace: argocd
  labels:
    crossplane.example.org: crossplane
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/altinukshini/crossplane-tutorial.git
    targetRevision: HEAD
    path: infrastructure/crossplane/aws/compositions
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m