# SQS Claim Example
# This is a "Claim" resource that creates an SQS queue using the xSQS composition
# Crossplane will create both a main queue and a dead-letter queue based on this single resource
apiVersion: example.org/v1alpha1
kind: SQS
metadata:
  name: test-sqs
spec:
  region: us-east-1
  # Reference to the provider configuration to use
  providerConfig: default
